### PR TITLE
[Feature] Export the evaluation summary table in csv format to the outputs folder

### LINKED ISSUE #221: [Feature] Export the evaluation summary table in csv format to the outputs folder
**Is your feature request related to a problem? Please describe.**
Currently when we use a evaluation.json file with `should_explain_scoring` as true, a table is printed in the console that explains how the scoring happened for a particular OMR sheet -
image

This is particularly useful for debugging complex answer keys with features such as section-wise marking, negative marking, bonus questions etc. ([ref](https://github.com/Udayraj123/OMRChecker/wiki/%5Bv2%5D-About-Evaluation#list-of-capabilities) for all capabilities)

Now there's no way to output this table as a separate CSV file per OMR sheet. 

**Describe the solution you'd like**
- Create a new folder named as `evaluation/` inside the outputs directory for each run (using the [outputs namespace](https://github.com/Udayraj123/OMRChecker/blob/bf19841b548d4181ff304cad75826299128f38cc/src/entry.py#L141)).
- Output filename can follow the same as input file name replacing the extension *.jpg with *.csv
- Check through the code trail for explanation_table in [evaluation.py](https://github.com/Udayraj123/OMRChecker/blob/bf19841b548d4181ff304cad75826299128f38cc/src/evaluation.py#L507) file and maintain a new object that holds the content for the csv. Preferably a pandas dataframe.
- We can use the `to_csv` util from pandas for exporting the csv from the evaluation class itself
- Add a flag to control this in the evaluation_schema.py file

**Describe alternatives you've considered**
N/A

**Additional context**
- Guide for the [Evaluation json file](https://github.com/Udayraj123/OMRChecker/wiki/%5Bv2%5D-About-Evaluation)
- Link to the [Discord invite](https://discord.gg/qFv2Vqf)
- Link to the [Hacktoberfest 2024 channel](https://discord.com/channels/590134763784896514/1284801897714155613/1284802010549321770)
- [Feature usecase reference](https://discord.com/channels/590134763784896514/590134763784896520/1290612742943670317)

### PR DESCRIPTION
**Pull request by tushar-badlani**
- added export_explanation_csv in options, this flag can be set to true to save explanations in csv in output folder
- changed evaluation.json in sample 4 to give an example for export_explanation_csv

fixes #221

### CODE REVIEW

**Comment by Udayraj123** [comment]
@tushar-badlani Thanks for the quick PR! Will go through it soon. 

Can you please rebase over the latest dev branch? I just saw there's some additional diff and now there's some conflicts introduced after that.

**Comment by tushar-badlani** [comment]
@Udayraj123 i merged my commits over latest dev branch

**Comment by Udayraj123** [comment]
@tushar-badlani the diff still seems high. Can you check again?

**Comment by Udayraj123** [comment]
crosslinking https://github.com/Udayraj123/OMRChecker/pull/228

**Pull request closed without merging**
