### PR TITLE
[Sample] new sample added(crop image preprocessor)

### PR DESCRIPTION
**Pull request by RohanHBTU**
This PR is related to issue #40.

### CODE REVIEW

**Comment by Udayraj123** [comment]
@RohanHBTU please share screenshots of output image with save_image_level = 4

**Comment by Udayraj123** [comment]
Would appreciate if you add one more image of the same OMR template. 
Also you need to put this one into the community folder with your username/nickname(without spaces). 

Sample7 etc are reserved for new functionalities.

**Comment by Udayraj123** [comment]
And see if you can make use of a new omr_marker.jpg that contains those square pointers on all 4 sides. It may need change in the ratio

**Comment by RohanHBTU** [comment]
> @RohanHBTU please share screenshots of output image with save_image_level = 4

Screenshot (79)

**Comment by RohanHBTU** [comment]
Please review my PR as I have done the changes as said.

**Comment by Udayraj123** [comment]
@RohanHBTU The name omr_marker.jpg is not for OMR scans. It's a special name for those 4 pointers on corners. You need to keep the names like omr-1.jpg, omr-2.jpg and so on. And lastly add another image omr_marker.jpg which contains one of the square boxes from the corner

**Comment by Udayraj123** [comment]
@RohanHBTU any updates?

**Pull request closed without merging**
