### PR TITLE
new OMR_template created

### PR DESCRIPTION
**Pull request by ShamanthVallem**
Added a new OMR Template(png file and template.json) in sample/community/shamanth

### CODE REVIEW

**Comment by Udayraj123** [comment]
To be taken as part of https://github.com/Udayraj123/OMRChecker/issues/40

**Comment by Udayraj123** [comment]
@ShamanthVallem please share screenshots of output image with save_image_level = 4 here in a comment

**Comment by ShamanthVallem** [comment]
Sure :)

**Review by Udayraj123 — APPROVED** [review]
LGTM

**Comment by Udayraj123** [comment]
@ShamanthVallem I am approving now, but before merging, can you make the bubbles smaller and move to center a bit?

**Comment by Udayraj123** [comment]
One more thing - compress your image to be under 200KB

**Comment by ShamanthVallem** [comment]
@Udayraj123 I made the mentioned changes and here is the new output

omr_scanner_output_shamanth

**Comment by ShamanthVallem** [comment]
I compressed the image to 110kb

**Comment by Udayraj123** [comment]
Much better! I will squash and merge so that commit history doesn't contain the larger sized images.

**Pull request merged**
