### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by bilal-aamer**
This addresses the Issue #35 

- 3. If tidy readable outputs interest you, try using colorama to indicate log levels

### CODE REVIEW

**Comment by pixalquarks** [comment]
I think you missed the whole point of logging in the code changes you made. We don't just want colored output, we need to log things out, and print is not the function for that.

**Comment by udayraj-rzp** [comment]
@pixalquarks actually colored output was part of one of the 4 tasks on that issue. But using colorama was debated. on the same issue. @bilal-aamer you need to use rich and do the same. I'll review both PRs soon and find a resolution

**Comment by Udayraj123** [comment]
@pixalquarks  actually colored output was part of one of the 4 tasks on that issue. But using colorama was debated. on the same issue. @bilal-aamer  you need to use rich and do the same. I'll review both PRs soon and find a resolution.

**Comment by pixalquarks** [comment]
What I mean is our first importance should be logging, since using print is not recommended to log stuffs. Also about colored outputs, we can just use rich for that too.

**Comment by bilal-aamer** [comment]
> What I mean is our first importance should be logging, since using print is not recommended to log stuffs. Also about colored outputs, we can just use rich for that too. 

Agreed will start on the rich part

**Comment by Udayraj123** [comment]
closing for now.. Feel free to open once code is ready.

**Pull request closed without merging**
