### PR TITLE
Dynamic contribution added

### PR DESCRIPTION
**Pull request by Harsh-Kapoorr**
Hey!! I have added the dynamic contribution section and also a visitor icon hope it helps.

### CODE REVIEW

**Comment by Udayraj123** [comment]
Hey @Harsh-Kapoorr let's move it just below the stargazers chart. Also visitors button is not needed we already have hits label at the top

**Comment by Harsh-Kapoorr** [comment]
Okay I get that I'll work on that and make it right and Push the changes.
After that I'll work on adding all contributors bot to readme it will look great

**Comment by Harsh-Kapoorr** [comment]
Now please check for the PR 
and Can I work on adding the bot?

**Comment by Udayraj123** [comment]
@Harsh-Kapoorr looks good, just can you add more user names from recent PRs merged today please?

**Comment by Sandeep-1507** [comment]
#75 [Sandeep-1507](https://github.com/Sandeep-1507)

**Comment by Harsh-Kapoorr** [comment]
Yes Sure!!

**Comment by SpyzzVVarun** [comment]
[#60](https://github.com/Udayraj123/OMRChecker/pull/60)    [#78](https://github.com/Udayraj123/OMRChecker/pull/78) [SpyzzVVarun](https://github.com/SpyzzVVarun)

**Pull request closed without merging**
